version: '3.1'
services:
  stats-server:
    build: stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-server
      - DB_NAME=stats-server
      - SPRING_DATASOURCE_USERNAME=owner
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=stats-db
      - DB_PORT=6541

  stats-db:
    image: postgres:14-alpine
    container_name: stats-server_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-server
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password