version: '3.1'
services:
  ewm-stats-service:
    build: ewm-stats-service
    image: ewm-stats-service-image
    container_name: ewm_stats_service_container
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/ewm_stats
      - DB_NAME=ewm_stats
      - SPRING_DATASOURCE_USERNAME=owner
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=ewm-stats-db
      - DB_PORT=6541

  ewm-stats-db:
    image: postgres:14-alpine
    container_name: ewm_stats_db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password

  ewm-main-service:
    build: ewm-main-service
    image: ewm_main_service_image
    container_name: ewm_main_service_container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-main-db
      - ewm-stats-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/ewm_main
      - DB_NAME=ewm_main
      - SPRING_DATASOURCE_USERNAME=owner
      - SPRING_DATASOURCE_PASSWORD=password
      - DB_HOST=ewm-db
      - DB_PORT=6542

  ewm-main-db:
    image: postgres:14-alpine
    container_name: ewm_main_service_db_container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=password