drop table if exists hits;
CREATE TABLE IF NOT EXISTS hits
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app        varchar(512)                            NOT NULL,
    uri        varchar(512)                            NOT NULL,
    ip         varchar(15)                             NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);